server:
  port: 8080
spring:
  application:
    name: api-gateway
#Register with Eureka service discovery
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

