server:
  port: 8082 #Optional: can be overriden by Config Server
spring:
  application:
    name: order-service # This name is used in WebClient URI
product-service:
  base-url: http://product-service/api/v1
inventory-service:
  base-url: http://inventory-service/api/v1
springdoc:
  swagger-ui:
    path: /swagger-ui.html #will be access at http://localhost:8082/swagger-ui.html
  api-docs:
    path: /v3/api-docs #will be access at http://localhost:8082/v3/api-docs
  default-produces-media-type: application/json #default produces media type for API responses
  default-consumes-media-type: application/json #default consumes media type for API requests
  override-with-gateway-url: true #override the default URL with the gateway URL







