
server:
  port: 8083
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ECommerce-Product-Service
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
api:
    endpoint:
        base-url: /api/v1
    redis:
        host: localhost
        port: 6379
        #port: 6000
        #timeout: 2000
        #cache-timeout: 3600

        cache-prefix: product-service
    cache:
        type: REDIS
    jackson:
        serialization:
        write-dates-as-timestamps: false #This ensures that dates are serialized as ISO-8601 formatted strings instead of Unix timestamps.
