spring:
  application:
    name: product-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: local


#When service starts, spring boot uses spring.application.name from this file to:
#1.Tell the config server: I am product-service, please give me product-service.yml from the
#applicationsConfiguration submodule. Check the config server's application.yml file
#2.Register with Eureka service discovery using the name product-service
#3. Identify itself for metrics, logging, service discovery, etc.
#So REPEATING spring.application.name IN THE product-service.yml file IS NOT NEEDED