server:
  port: 8084
spring:
  application:
    name: inventory-service # This name is used in WebClient URI
  datasource:
    url: jdbc:postgresql://localhost:5432/ECommerce-Inventory-Service
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    com.tjtechy.common-utils.RedisCacheConfig: INFO
#api:
#  endpoint:
#    base-url: /api/v1
