server:
  port: 8084
spring:
  application:
    name: inventory-service # This name is used in WebClient URI
product-service:
  base-url: http://product-service/api/v1
inventory-service:
  base-url: http://inventory-service/api/v1
    # This is the base URL for the Product Service, which is used in WebClient calls
springdoc:
  swagger-ui:
    path: /swagger-ui.html #will be access at http://localhost:8084/swagger-ui.html
  api-docs:
    path: /v3/api-docs #will be access at http://localhost:8084/v3/api-docs
  default-produces-media-type: application/json #default produces media type for API responses
  default-consumes-media-type: application/json #default consumes media type for API requests
  override-with-gateway-url: true #override the default URL with the gateway URL
management:
  endpoints:
    web:
      exposure:
        #health,customes-beans,httpexchanges all have custom implementation in the system module
        include: health,info,metrics,env,beans,configprops,heapdump,httpexchanges,loggers,mappings,customs-beans,prometheus
  tracing:
    enabled: true
    sampling:
      probability: 1.0 # Adjust the sampling probability as needed (0.0 to 1.0)
tracing:
  #url: http://ecommerce-jaeger:4318/v1/traces # OTLP endpoint for Jaeger in docker-compose environment
  url: ${TRACING_URL:http://localhost:4318/v1/traces} #OTLP endpoint for Jaeger in local environment,defaults to localhost if not set.In docker-compose,it will be set to: http://ecommerce-jaeger:4318/v1/traces

#    exporter:
#      otlp:
#        endpoint: http://ecommerce-jaeger:4318/v1/traces # OTLP endpoint for OpenTelemetry Collector
#        endpoint: http://ecommerce-jaeger:4317 # OTLP endpoint for OpenTelemetry Collector
  endpoint:
    health:
      show-details: always #show details in the health endpoint
    #TODO: httpexchanges should not be enabled in production as it can expose sensitive information,when security service is implemented, this can be enabled
    httpexchanges:
      enabled: false #enable http exchanges endpoint, now disabled for security reasons
    env:
      show-values: always #show values in the env endpoint
    configprops:
      show-values: always #show values in the configprops endpoint
    info:
      build:
        enabled: true
      env:
        enabled: true
      git:
        enabled: true
      java:
        enabled: true
      os:
        enabled: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [${spring.application.name}] [traceId=%X{traceId}, spanId=%X{spanId}] %-5level %logger{36} - %msg%n" # Custom log pattern
    file: "%d{yyyy-MM-dd HH:mm:ss} [${spring.application.name}] [traceId=%X{traceId}, spanId=%X{spanId}] %-5level %logger{36} - %msg%n"
  file:
    name: ./logs/inventory-service/app.log # Log file path
  #increase tracing verbosity for debugging
#  level:
#    io.micrometer.tracing: DEBUG
#    io.opentelemetry.exporter.otlp: DEBUG

info:
  app:
    name:
    description: Inventory Service
    version: @project.version@ #retrieved from pom.xml
    author: Tajudeen Busari (tjtechy)
    links:
      github: https://github.com/TajudeenBusari/EcommerceAPI/tree/master/inventory-service



