server:
  port: 0 # Set to 0 to use a random port for testing
spring:
    application:
        name: common-utils
    profiles:
        active: allTests
    datasource:
        url: ${POSTGRES_URL} #Dynamically set by the test container.
        username: testuser #Dynamically set by the test container.
        password: testpassword #Dynamically set by the test container.
        driver-class-name: org.postgresql.Driver
    redis:
        host: ${REDIS_HOST} #Dynamically set by the test container.
        port: ${REDIS_PORT} #Dynamically set by the test container.
        cache-prefix: common-utils
    cache:
        type: REDIS
    jpa:
        hibernate:
        ddl-auto: create-drop
        show-sql: true