server:
  port: 8763
spring:
  application:
    name: eureka-server
    #disble jarkata.validationNoProviderFoundException showing in the logs
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.validation.ValidationAutoConfiguration

eureka:
  client:
    register-with-eureka: false #DISABLING THE REGISTRATION OF THE EUREKA-SERVER WITH ITSELF
    fetch-registry: false #DISABLING THE FETCHING OF REGISTRY FROM ITSELF
    service-url:
      #defaultZone: "http://localhost:8762/eureka" #URL FOR THE EUREKA SERVER
      defaultZone: "http://localhost:${server.port}/eureka"
  server:
    wait-time-in-ms-when-sync-empty: 0 #TIME TO WAIT WHEN SYNC IS EMPTY
    enable-self-preservation: false #DISABLE SELF PRESERVATION MODE

logging:
  level:
    com.netflix.eureka: INFO #SET THE LOG LEVEL FOR EUREKA TO INFO
    com.netflix.discovery: INFO #SET THE LOG LEVEL FOR DISCOVERY TO INFO
    com.netflix.eureka.cluster.peerEurekaNodes: INFO #SET THE LOG LEVEL FOR EUREKA CLUSTER TO DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [${spring.application.name}] [traceId=%X{traceId}, spanId=%X{spanId}] %-5level %logger{36} - %msg%n" # Custom log pattern
    file: "%d{yyyy-MM-dd HH:mm:ss} [${spring.application.name}] [traceId=%X{traceId}, spanId=%X{spanId}] %-5level %logger{36} - %msg%n"
  file:
    name: ./logs/eureka-server/app.log # Log file path

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,beans,configprops,heapdump,httpexchanges,loggers,mappings,customs-beans,prometheus
  endpoint:
    health:
      show-details: always #show details in the health endpoint
  env:
    show-values: always #show values in the env endpoint
  configprops:
    show-values: always #show values in the configprops endpoint
  info:
    build:
      enabled: true
    env:
      enabled: true
    git:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  tracing:
    sampling:
      probability: 1.0 # Adjust the sampling probability as needed (0.0 to 1.0)
  otlp:
    tracing:
      endpoint: http://jaeger:4318 # send traces to jaeger
info:
  app:
    name:
    description: Eureka Server
    version: @project.version@ #retrieved from pom.xml
    author: Tajudeen Busari (tjtechy)
    links:
      github: https://github.com/TajudeenBusari/EcommerceAPI/tree/master/eureka-server





