server:
  port: 8761
spring:
  application:
    name: eureka-server
eureka:
  client:
    register-with-eureka: false #DISABLING THE REGISTRATION OF THE EUREKA-SERVER WITH ITSELF
    fetch-registry: false #DISABLING THE FETCHING OF REGISTRY FROM ITSELF



