server:
    port: 8888
spring:
    application:
        name: config-server
    cloud:
        config:
        server:
            git:
            uri: https://github.com/TajudeenBusari/EcommerceAPI
            search-paths: applicationConfig # Folder containing config files
            default-label: master
            clone-on-start: false
#Register with Eureka service discovery
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
