name: Ecommerce build and deploy a container to an Azure Container App

env:
  AZURE_RESOURCE_GROUP: ecommerce-java-resource-group
  AZURE_CONTAINERAPPS_ENVIRONMENT: ecommerce-container-apps-env
  AZURE_LOCATION: swedencentral
  #AZURE_WEBAPP_NAME: ecommerce-java-web-app #no longer used, replaced by AZURE_CONTAINERAPPS_ENVIRONMENT
  FIREBASE_CONFIG_BASE64: ${{ secrets.FIREBASE_CONFIG_BASE64 }}
  JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
  JWT_PUBLIC_KEY: ${{ secrets.JWT_PUBLIC_KEY }}

on:
  push:
    branches:
      - master

permissions:
  contents: 'read'
  packages: 'write'
  id-token: 'write'

jobs:
  #======================================================================#
    #first job builds all modules and skips tests.
    #Just want the executable jar files to be built
    #and cached for the next job to deploy the container to Azure Web App
  #======================================================================#
  build:
    name: Build All Modules
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      - name: Decode and save Firebase config
        run: |
          echo "$FIREBASE_CONFIG_BASE64" | base64 -d > firebase-service-config.json

      - name: Create JWT Key files
        run: |
          mkdir -p user-service/src/main/resources/certs
          printf "%s" "$JWT_PRIVATE_KEY" > user-service/src/main/resources/certs/private.pem
          printf "%s" "$JWT_PUBLIC_KEY" > user-service/src/main/resources/certs/public.pem

      - name: Build all Maven modules (skipping tests)
        run: |
          mvn --batch-mode clean install -DskipTests

      - name: Upload Maven target directory
        uses: actions/upload-artifact@v4
        with:
          name: maven-targets
          path: |
            api-gateway/target
            config-server/target
            eureka-server/target
            inventory-service/target
            notification-service/target
            order-service/target
            product-service/target
            user-service/target
          retention-days: 1

  #=====================================================#
    #Build and push one Docker image per microservice.
  #=====================================================#
  docker:
    name: Build and Push ${{ matrix.service }} Docker Image
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service:
          - api-gateway
          - config-server
          - eureka-server
          - inventory-service
          - notification-service
          - order-service
          - product-service
          - user-service
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Download Maven target directories from previous job
        uses: actions/download-artifact@v4
        with:
          name: maven-targets
          path: .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase the repo name
        run: | 
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push ${{ matrix.service }} image
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.REPO }}/${{ matrix.service }}:${{ github.sha }}
            ghcr.io/${{ env.REPO }}/${{ matrix.service }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # ============================================================
  # Create Azure Container Apps environment
  # ============================================================
  create-container-app-environment:
    name: Create Azure Container App Environment
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login using Github OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-oidc: true

      - name: Install Azure Container Apps Extension
        run: |
          az extension add --name containerapp --upgrade

      - name: Create resource group if it does not exist
        run: |
          az group create --name ${{ env.AZURE_RESOURCE_GROUP }} --location ${{ env.AZURE_LOCATION }}

      - name: Create Azure Container Apps Environment
        run: |
         if az containerapp env show --name ${{ env.AZURE_CONTAINERAPPS_ENVIRONMENT}} --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            > /dev/null 2>&1; then
                echo "Azure Container Apps Environment already exists."
            else
                az containerapp env create \
                --name ${{ env.AZURE_CONTAINERAPPS_ENVIRONMENT }} \
                --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
                --location ${{ env.AZURE_LOCATION }}
            fi

  #===========================================================
  #    Deploy Eureka server first. Eureka does not depend on Config server
  #   Config server depends on Eureka server
  #===========================================================
  deploy-eureka:
    name: Deploy Eureka Server
    needs: create-container-app-environment
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login using GitHub OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-oidc: true

      - name: Install Azure Container Apps Extension
        run: |
          az extension add --name containerapp --upgrade

      - name: Lowercase the repo name
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Create or Update Eureka Server
        run: |
          IMAGE="ghcr.io/${REPO}/eureka-server:${{ github.sha }}"
          
          if az containerapp show \
            --name ecommerce-eureka-server \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            > /dev/null 2>&1; then
          
            echo "Container App ecommerce-eureka-server already exists. Updating..."
            
            az containerapp update \
              --name ecommerce-eureka-server \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
              --image "$IMAGE"
             
          else
          
            echo "Container App does not exist. Creating ..."
          
            az containerapp create \
              --name ecommerce-eureka-server \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
              --environment ${{ env.AZURE_CONTAINERAPPS_ENVIRONMENT }} \
              --image "$IMAGE" \
              --ingress internal \
              --target-port 8763 \
              --registry-server ghcr.io \
              --registry-username ${{ github.actor }} \
              --registry-password "${{ secrets.GITHUB_TOKEN }}" \
              --min-replicas 1 \
              --max-replicas 1
          fi
      - name: Wait for Eureka Server readiness
        shell: bash
        run: |
          echo "Waiting for Eureka Server to be ready..."
          for i in {1..30}; do
          
            STATUS=$(az containerapp show \
              --name ecommerce-eureka-server \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
              --query "properties.runningState" \
              -o tsv 2>/dev/null || true)
          
            echo "Attempt $i/30 - Eureka status: $STATUS"
            
            if [ "$STATUS" = "Running" ]; then
              echo "Eureka Container App is running."
              break
            fi
          
            if [ "$i" -eq 30 ]; then
              echo "Eureka Server did not become ready."
              exit 1
            fi
          
            sleep 10
          
          done

  #===========================================================
  #   Deploy Config server next. Config server depends on Eureka server
  #===========================================================
  deploy-config-server:
    name: Deploy Config Server
    needs: deploy-eureka
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login using GitHub OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-oidc: true

      - name: Install Azure Container Apps Extension
        run: |
          az extension add --name containerapp --upgrade

      - name: Lowercase the repo name
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Get Eureka Server FQDN
        run: |
          EUREKA_FQDN=$(az containerapp show \
            --name ecommerce-eureka-server \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --query "properties.configuration.ingress.fqdn" \
            -o tsv)
          
          echo "EUREKA_SERVER_URL=http://${EUREKA_FQDN}:8763/eureka/" >>${GITHUB_ENV}
          echo "Eureka URL:"
          echo "$EUREKA_SERVER_URL"

      - name: Create or Update Config Server
        run: |
          IMAGE="ghcr.io/${REPO}/config-server:${{ github.sha }}"
          
          if az containerapp show \
            --name ecommerce-config-server \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            > /dev/null 2>&1; then
          
            echo "Container App ecommerce-config-server already exists. Updating..."
            
            az containerapp update \
              --name ecommerce-config-server \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
              --image "$IMAGE" \
              --set-env-vars EUREKA_SERVER_URL="$EUREKA_SERVER_URL"
          
          else
          
            echo "Container App does not exist. Creating ..."
          
            az containerapp create \
              --name ecommerce-config-server \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
              --environment ${{ env.AZURE_CONTAINERAPPS_ENVIRONMENT }} \
              --image "$IMAGE" \
              --ingress internal \
              --target-port 8888 \
              --registry-server ghcr.io \
              --registry-username ${{ github.actor }} \
              --registry-password "${{ secrets.GITHUB_TOKEN }}" \
              --min-replicas 1 \
              --max-replicas 1 \
              --env-vars EUREKA_SERVER_URL="$EUREKA_SERVER_URL"
          fi
      - name: Wait for Config Server readiness
        shell: bash
        run: |
          echo "Waiting for Config Server to be ready..."
          for i in {1..30}; do
          
            STATUS=$(az containerapp show \
              --name ecommerce-config-server \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
              --query "properties.runningState" \
              -o tsv 2>/dev/null || true)
          
            echo "Attempt $i/30 - Config Server status: $STATUS"
            
            if [ "$STATUS" = "Running" ]; then
              echo "Config Container App is running."
              break
            fi
          
            if [ "$i" -eq 30 ]; then
              echo "Config Server did not become ready."
              exit 1
            fi
          
            sleep 10
          
          done

  # ============================================================
  # Deploy other microservices to Azure Container Apps
  # ============================================================
  deploy:
    name: Deploy ${{ matrix.service }} to Azure Container Apps
    needs: deploy-config-server
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        include:

          # API Gateway - PUBLIC
          - service: api-gateway
            container_app: ecommerce-api-gateway
            port: 8080
            ingress: external

          # Inventory Service - INTERNAL
          - service: inventory-service
            container_app: ecommerce-inventory-service
            port: 8084
            ingress: internal

          # Notification Service - INTERNAL
          - service: notification-service
            container_app: ecommerce-notification-service
            port: 8085
            ingress: internal

          # Order Service - INTERNAL
          - service: order-service
            container_app: ecommerce-order-service
            port: 8082
            ingress: internal

          # Product Service - INTERNAL
          - service: product-service
            container_app: ecommerce-product-service
            port: 8083
            ingress: internal

          # User Service - INTERNAL
          - service: user-service
            container_app: ecommerce-user-service
            port: 8086
            ingress: internal

    steps:
      - name: Azure Login using Github OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }} #
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-oidc: true

      - name: Install Azure Container Apps Extension
        run: |
          az extension add --name containerapp --upgrade

      - name: Lowercase the repo name
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Get Eureka Server FQDN
        run: |
          EUREKA_FQDN=$(az containerapp show \
            --name ecommerce-eureka-server \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --query "properties.configuration.ingress.fqdn" \
            -o tsv)
          
          EUREKA_SERVER_URL="http://${EUREKA_FQDN}:8763/eureka/"
          
          echo "EUREKA_SERVER_URL=$EUREKA_SERVER_URL" >>$GITHUB_ENV
          echo "Eureka URL: $EUREKA_SERVER_URL"

      - name: Get Config Server FQDN
        run: |
          CONFIG_FQDN=$(az containerapp show \
            --name ecommerce-config-server \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --query "properties.configuration.ingress.fqdn" \
            -o tsv)
          
          CONFIG_SERVER_URL="http://${CONFIG_FQDN}:8888"
          echo "CONFIG_SERVER_URL=$CONFIG_SERVER_URL" >>${GITHUB_ENV}
          echo "Config URL: $CONFIG_SERVER_URL"

      - name: Create or Update ${{ matrix.container_app}}
        run: |
          IMAGE="ghcr.io/${{ env.REPO }}/${{ matrix.service }}:${{ github.sha }}"
          
          echo "Deploying"
          echo " Service: ${{ matrix.service }}"
          echo " Container App: ${{ matrix.container_app }}"
          echo " Image: $IMAGE"
          echo " Port: ${{ matrix.port }}"
          echo " Ingress: ${{ matrix.ingress }}"
          echo "Eureka URL: $EUREKA_SERVER_URL"
          echo "Config URL: $CONFIG_SERVER_URL"
          
          if az containerapp show \
            --name ${{ matrix.container_app }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            > /dev/null 2>&1; then
          
            echo "Container App ${{ matrix.container_app }} already exists. Updating..."
            
            az containerapp update \
              --name ${{ matrix.container_app }} \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
              --image "$IMAGE" \
              --set-env-vars \
                EUREKA_SERVER_URL="$EUREKA_SERVER_URL" \
                CONFIG_SERVER_URL="$CONFIG_SERVER_URL"
          
          else
          
            echo "Container App does not exist. Creating ..."
            
            az containerapp create \
              --name ${{ matrix.container_app }} \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
              --environment ${{ env.AZURE_CONTAINERAPPS_ENVIRONMENT }} \
              --image "$IMAGE" \
              --ingress ${{ matrix.ingress }} \
              --target-port ${{ matrix.port }} \
              --registry-server ghcr.io \
              --registry-username ${{ github.actor }} \
              --registry-password "${{ secrets.GITHUB_TOKEN }}" \
              --min-replicas 1 \
              --max-replicas 1 \
              --env-vars \
                EUREKA_SERVER_URL="$EUREKA_SERVER_URL" \
                CONFIG_SERVER_URL="$CONFIG_SERVER_URL"
          
          fi
